version: '3.9'
services:
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: lucky_kangaroo
      POSTGRES_USER: lk
      POSTGRES_PASSWORD: lkpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
      - "9600:9600"

  kibana:
    image: opensearchproject/opensearch-dashboards:2.11.0
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    depends_on:
      - opensearch

volumes:
  pgdata:
